alias rn='react-native'
alias rns='react-native start'
alias rnlink='react-native link'

alias rnand='react-native run-android'
alias rnandvr='react-native run-android --variant=release'
alias rnios='react-native run-ios'
alias rnios4s='react-native run-ios --simulator "iPhone 4s"'
alias rnios5='react-native run-ios --simulator "iPhone 5"'
alias rnios5s='react-native run-ios --simulator "iPhone 5s"'
alias rnios6='react-native run-ios --simulator "iPhone 6"'
alias rnios6s='react-native run-ios --simulator "iPhone 6s"'
alias rnios7='react-native run-ios --simulator "iPhone 7"'
alias rnios8='react-native run-ios --simulator "iPhone 8"'
alias rniosx='react-native run-ios --simulator "iPhone X"'
alias ry='rm -rf node_modules && yarn'
alias ryc='ry && cd ./node_modules/react-native && $PWD/scripts/ios-install-third-party.sh && cd ../../'
alias rya='ry && rnand'
alias ryi='ryc && rnios7'
alias ryi6='ryc && rnios6'
alias ryi6s='ryc && rnios6s'
alias ryi7='ryc && rnios7'
alias ryi8='ryc && rnios8'
alias ryix='ryc && rniosx'
alias myip='ipconfig getifaddr en0'
alias sonosmysql='mysql.server start'
alias sonosmem='memcached -d'
